import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const BUSINESS=[['retail','🛍️','Retail Store / Boutique'],['cafe','☕','Coffee Shop / Café'],['qsr','🍔','Quick-Service Restaurant'],['restaurant','🍽️','Restaurant'],['salon','💇','Salon / Barbershop'],['spa','💆','Spa / Wellness'],['general','🏪','Convenience / General Store'],['wholesale','📦','Wholesale / Distribution'],['service','🧾','Service Business'],['other','⚙️','Other']];
const SELL=[['coffee','☕','Coffee & Espresso'],['milk','🧋','Milk Tea / Specialty Drinks'],['noncoffee','🥤','Non-Coffee Beverages'],['pastry','🍰','Pastries & Desserts'],['meal','🥪','Sandwiches & Light Meals'],['breakfast','🍳','Breakfast / Brunch'],['icecream','🍨','Ice Cream / Gelato'],['merch','🛍️','Retail Coffee Beans / Merchandise'],['mixed','🍽️','Mixed Café Menu'],['other','➕','Other']];
const LANG=[['en','🇬🇧','English'],['fil','🇵🇭','Filipino'],['both','🌐','English + Filipino']];const CUR=[['PHP','🇵🇭','PHP — Philippine Peso'],['USD','🇺🇸','US Dollar — USD'],['OTHER','💱','Other']];
const DEFAULT=[['Classic Milk Tea','Beverages',95,24],['Brown Sugar Boba','Beverages',120,18],['Wintermelon Tea','Beverages',105,31],['Taro Milk Tea','Beverages',110,12],['Matcha Latte','Beverages',125,8],['Cheese Foam Tea','Beverages',135,6]].map((x,i)=>({id:i+1,name:x[0],category:x[1],price:x[2],stock:x[3]}));
const money=(n,c)=>{const v=Number(n)||0;return c==='PHP'?'₱'+v.toLocaleString('en-PH',{minimumFractionDigits:2}):c==='USD'?'$'+v.toLocaleString('en-US',{minimumFractionDigits:2}):v.toLocaleString(undefined,{minimumFractionDigits:2})+' '+(c||'PHP')};
const readJSON=(key,fallback)=>{try{const raw=localStorage.getItem(key);if(raw==null)return fallback;const v=JSON.parse(raw);return v??fallback}catch{return fallback}};
const readArray=(key)=>{const v=readJSON(key,[]);return Array.isArray(v)?v:[]};
const DEFAULT_MODULES={sale:true,inventory:true,products:true,reports:true,customers:false,purchasing:false,suppliers:false,expenses:false,loyalty:false,tables:false,appointments:false,delivery:false};
const DEFAULT_PERMISSIONS={owner:{sale:true,inventory:true,products:true,reports:true,settings:true},manager:{sale:true,inventory:true,products:true,reports:true,settings:false},cashier:{sale:true,inventory:false,products:false,reports:false,settings:false},inventory:{sale:true,inventory:true,products:true,reports:false,settings:false}};

function Tile({x,selected,onClick}){return <button className={'tile '+(selected?'chosen':'')} onClick={onClick}><span>{x[1]}</span><b>{x[2]}</b>{selected&&<i>✓</i>}</button>}
function PosLogo(){
 return <svg className="poslogo" viewBox="0 0 160 120" aria-label="POS terminal">
  <rect x="19" y="13" width="122" height="66" rx="9" fill="#171b20" stroke="#7d8795" strokeWidth="5"/>
  <rect x="29" y="23" width="102" height="46" rx="5" fill="#0c1015"/>
  <g fill="#168cff"><rect x="38" y="31" width="20" height="12" rx="2"/><rect x="64" y="31" width="20" height="12" rx="2"/><rect x="90" y="31" width="20" height="12" rx="2"/><rect x="38" y="49" width="20" height="12" rx="2"/><rect x="64" y="49" width="20" height="12" rx="2"/><rect x="90" y="49" width="20" height="12" rx="2"/></g>
  <rect x="48" y="78" width="72" height="23" rx="5" fill="#15191e" stroke="#68717d" strokeWidth="4"/>
  <circle cx="84" cy="89" r="5" fill="#8c96a3"/>
  <rect x="123" y="55" width="23" height="48" rx="4" fill="#20252b" stroke="#707987" strokeWidth="4"/>
  <path d="M126 55h17v13h-17z" fill="#f1f3f5"/>
  <path d="M128 59h13M128 63h13M128 67h10" stroke="#9aa3ad" strokeWidth="2"/>
 </svg>
}

function Login({done}){
 const TEST={username:"test",password:"test",pin:"062396",name:"Test Account"};
 const [mode,setMode]=useState("signin"),[e,setE]=useState(""),[p,setP]=useState(""),[pin,setPin]=useState(""),[name,setName]=useState(""),[confirm,setConfirm]=useState(""),[err,setErr]=useState(""),[notice,setNotice]=useState("");
 const users=()=>{try{return JSON.parse(localStorage.getItem("omnipos_users")||"{}")}catch{return {}}};
 const saveUsers=u=>localStorage.setItem("omnipos_users",JSON.stringify(u));
 const ensureTest=()=>{const u=users();if(!u.test){u.test=TEST;saveUsers(u)}return u};
 const signIn=a=>{a.preventDefault();setErr("");setNotice("");const u=ensureTest(),key=e.trim().toLowerCase(),account=u[key]||Object.values(u).find(x=>x.email?.toLowerCase()===key);if(account&&account.password===p){localStorage.setItem("omnipos_user",account.username||key);localStorage.setItem("omnipos_role","owner");localStorage.setItem("omnipos_owner_pin",account.pin);done(account.username||key)}else setErr("Invalid username/email or password.")};
 const create=a=>{a.preventDefault();setErr("");setNotice("");if(!name.trim()||!e.trim()||!p||p!==confirm){setErr("Complete all fields and make sure the passwords match.");return}if(!/^\d{6}$/.test(pin)){setErr("Owner switch PIN must be exactly 6 numerical digits.");return}const u=ensureTest(),key=e.trim().toLowerCase();if(u[key]){setErr("An account with this username/email already exists.");return}const account={username:key,email:key,password:p,pin,name:name.trim()};u[key]=account;saveUsers(u);localStorage.setItem("omnipos_user",key);localStorage.setItem("omnipos_role","owner");localStorage.setItem("omnipos_owner_pin",pin);done(key)};
 const reset=()=>{if(window.confirm("Reset OmniPOS local data? This removes accounts, setup, products, sales and settings on this device.")){localStorage.clear();setE("");setP("");setPin("");setName("");setConfirm("");setErr("");setNotice("Local data reset. The test account (test / test / PIN 062396) will be available again after the next sign-in attempt.")}};
 return <div className="auth">
   <div className="authleft"><div className="version">OmniPOS v1.9.0</div><div className="leftcontent"><div className="wordmark">Omni<span>POS</span></div><div className="tagline">Universal Point of Sale</div><p className="hero">One system. Any business.<br/>Built to help you sell, manage,<br/>and grow.</p><div className="features"><div><strong>🛒</strong><span><b>Sell Faster</b><small>Simple and efficient checkout</small></span></div><div><strong>▥</strong><span><b>Track Everything</b><small>Inventory, sales, and reports</small></span></div><div><strong>⚙</strong><span><b>Built for Any Business</b><small>Retail, Food, Services and more</small></span></div><div><strong>☁</strong><span><b>Your Business, Your Way</b><small>Flexible, customizable, and scalable</small></span></div></div><div className="growth">More Than a POS<br/>A Partner in Your Growth</div></div></div>
   <div className="authright"><div className="authcard"><PosLogo/><h1>Omni<span>POS</span></h1><p>Universal Point of Sale</p>
    {mode==="signin"?<form onSubmit={signIn} autoComplete="off"><label>Username or Email<input type="text" name="omnipos-login-user" autoComplete="off" autoCorrect="off" autoCapitalize="off" spellCheck="false" value={e} onChange={a=>{setE(a.target.value);setErr("")}} placeholder="Username or email"/></label><label>Password<input type="password" name="omnipos-login-pass" autoComplete="new-password" autoCorrect="off" autoCapitalize="off" spellCheck="false" value={p} onChange={a=>{setP(a.target.value);setErr("")}} placeholder="••••••••"/></label>{err&&<div className="error">{err}</div>}{notice&&<div className="notice">{notice}</div>}<button className="primary full signin">Sign In <span>→</span></button><div className="or"><i></i><span>OR</span><i></i></div><button type="button" className="signupbtn full" onClick={()=>{setMode("signup");setErr("");setNotice("")}}>Sign Up <span>♙+</span></button><small className="newuser">New to OmniPOS? Create an account to get started.</small><button type="button" className="forgot" onClick={()=>setErr("Password recovery will be connected to your account service.")}>Forgot Password?</button><button type="button" className="reset-data" onClick={reset}>Reset Data / Login</button></form>
    :<form onSubmit={create} autoComplete="off"><button type="button" className="backlink" onClick={()=>{setMode("signin");setErr("")}}>← Back to Sign In</button><h2>Create your account</h2><label>Business / Owner Name<input value={name} onChange={a=>setName(a.target.value)} placeholder="Your business name"/></label><label>Username or Email<input type="text" name="omnipos-signup-user" autoComplete="off" autoCorrect="off" autoCapitalize="off" spellCheck="false" value={e} onChange={a=>setE(a.target.value)} placeholder="Choose a username or email"/></label><label>Password<input type="password" name="omnipos-signup-pass" autoComplete="new-password" autoCorrect="off" autoCapitalize="off" spellCheck="false" value={p} onChange={a=>setP(a.target.value)} placeholder="Create a password"/></label><label>Confirm Password<input type="password" name="omnipos-signup-confirm" autoComplete="new-password" autoCorrect="off" autoCapitalize="off" spellCheck="false" value={confirm} onChange={a=>setConfirm(a.target.value)} placeholder="Repeat your password"/></label><label>6-Digit Owner Switch PIN<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} type="password" autoComplete="new-password" autoCorrect="off" autoCapitalize="off" spellCheck="false" name="new-owner-switch-pin" value={pin} onChange={a=>setPin(a.target.value.replace(/\D/g,"").slice(0,6))} placeholder="••••••" /><small className="field-help">Exactly 6 numbers. Used when Staff switches to Owner Mode.</small></label>{err&&<div className="error">{err}</div>}<button className="primary full">Create Account <span>→</span></button><small className="newuser">Your POS setup starts after account creation.</small></form>}
   </div><footer><span>Made for Your Business ♥</span><span>© 2026 OmniPOS. All rights reserved.</span><span>Version 1.9.0</span></footer></div>
 </div>
}

function Setup({done}){const[step,setStep]=useState(1),[b,setB]=useState(''),[s,setS]=useState([]),[l,setL]=useState(''),[c,setC]=useState('');const toggle=x=>setS(v=>v.includes(x)?v.filter(q=>q!==x):[...v,x]);return <div className="setup"><div className="setupcard"><div className="step">INITIAL SETUP • {step}/3</div>{step===1&&<><h1>What type of business do you operate?</h1><p>This setup is shown only the first time.</p><div className="tiles">{BUSINESS.map(x=><Tile key={x[0]} x={x} selected={b===x[0]} onClick={()=>setB(x[0])}/>)}</div><button className="primary" disabled={!b} onClick={()=>setStep(2)}>Continue</button></>}{step===2&&<><h1>What do you primarily sell?</h1><p>Choose one or more. You can change products later.</p><div className="tiles">{SELL.map(x=><Tile key={x[0]} x={x} selected={s.includes(x[0])} onClick={()=>toggle(x[0])}/>)}</div><div className="actions"><button className="secondary" onClick={()=>setStep(1)}>Back</button><button className="primary" disabled={!s.length} onClick={()=>setStep(3)}>Continue</button></div></>}{step===3&&<><h1>Choose your language & currency</h1><h3>Language</h3><div className="tiles three">{LANG.map(x=><Tile key={x[0]} x={x} selected={l===x[0]} onClick={()=>setL(x[0])}/>)}</div><h3>Currency</h3><div className="tiles three">{CUR.map(x=><Tile key={x[0]} x={x} selected={c===x[0]} onClick={()=>setC(x[0])}/>)}</div><div className="actions"><button className="secondary" onClick={()=>setStep(2)}>Back</button><button className="primary" disabled={!l||!c} onClick={()=>{localStorage.setItem('omnipos_config',JSON.stringify({business:b,selling:s,language:l,currency:c,tax:c==='PHP'?12:0,taxEnabled:true,setupDone:true,businessName:'',ownerPin:'',modules:{...DEFAULT_MODULES},advancedMode:true,guestCheckout:true,holdOrders:true,paymentConfirmation:true,trackInventory:true,lowStockAlerts:true,zeroStockAlerts:true}));done()}}>Finish Setup</button></div></>}</div></div>}


function ReceiptPreview({config,products,currency}){
 const [printer,setPrinter]=useState(null),[detecting,setDetecting]=useState(false);
 const sample=products?.[0]||{name:"Classic Milk Tea",price:95,category:"Beverages"};
 const second=products?.[1]||{name:"Brown Sugar Boba",price:120};
 const taxEnabled=config.taxEnabled!==false, rate=Number(config.tax)||0, subtotal=Number(sample.price||95)+Number(second.price||120), tax=taxEnabled?subtotal*rate/100:0, total=subtotal+tax;
 const header=config.receiptHeader||config.businessName||"OmniPOS Café", addr1=config.receiptAddress1||config.address1||"143 Doty Circle, West Springfield",addr2=config.receiptAddress2||config.address2||"MA 01089, USA",phone=config.receiptPhone||config.phone||"(413) 732-3899",footer=config.receiptFooter||"THANK YOU FOR DINING WITH US!\nPLEASE COME AGAIN";
 const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
 const detect=async()=>{setDetecting(true);const found=[];if("bluetooth" in navigator)found.push({type:"Bluetooth",status:"Available to pair"});if("usb" in navigator)found.push({type:"Wired / USB",status:"Available to request"});found.push({type:"Wi-Fi / Network",status:"Needs network/native printer discovery"});setPrinter(found);setDetecting(false)};
 const printTest=()=>{const width=config.receiptWidth||"80mm";const cssWidth=width==="58mm"?"58mm":width==="80mm"?"80mm":"280mm";const html=`<!doctype html><html><head><title>OmniPOS Test Receipt</title><style>@page{size:${width==="A4"?"A4":width+" auto"};margin:0}body{font-family:Arial,sans-serif;width:${cssWidth};margin:0;padding:12px;box-sizing:border-box;font-size:12px;color:#111}h2{text-align:center;margin:0 0 7px;font-size:20px}p{margin:3px 0;text-align:center}.sep{border-top:2px dashed #777;margin:10px 0}.center{text-align:center}.line{display:flex;justify-content:space-between;gap:10px;margin:5px 0}.item{display:grid;grid-template-columns:35px 1fr 75px;gap:5px;margin:7px 0}.item span:last-child{text-align:right}.pay{display:flex;justify-content:space-between;font-weight:bold;margin:8px 0}.total{display:flex;justify-content:space-between;font-weight:800;font-size:16px;margin-top:13px}.barcode{height:44px;margin:14px auto 0;width:72%;background:repeating-linear-gradient(90deg,#111 0 2px,#fff 2px 4px,#111 4px 5px,#fff 5px 8px,#111 8px 11px,#fff 11px 13px)}.foot{white-space:pre-line;line-height:1.5}</style></head><body><div class="sep"></div><h2>${esc(header)}</h2><p>${esc(addr1)}</p><p>${esc(addr2)}</p><p>${esc(phone)}</p><p>${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p><p>Table No. <b>2</b> Bill No. 101</p><div class="sep"></div><div class="item"><b>QTY</b><b>ITEM</b><b>PRICE</b></div><div class="item"><span>1</span><span>${esc(sample.name)}</span><span>${money(Number(sample.price),currency)}</span></div><div class="item"><span>1</span><span>${esc(second.name)}</span><span>${money(Number(second.price),currency)}</span></div><div class="sep"></div><div class="pay"><span>VISA 2535</span><span>SALE</span></div><div class="line"><span>SUBTOTAL</span><span>${money(subtotal,currency)}</span></div><div class="line"><span>TAX</span><span>${money(tax,currency)}</span></div><div class="line"><span>TRANSACTION TYPE:</span><span>SALE</span></div><div class="line"><span>AUTHORIZATION:</span><span>APPROVED</span></div><div class="line"><span>PAYMENT CODE:</span><span>TEST-98871477</span></div><div class="line"><span>PAYMENT ID:</span><span>TEST-276131704</span></div><div class="line"><span>CARD READER:</span><span>SWIPED/CHIP</span></div><div class="sep"></div><div class="total"><span>=TOTAL:</span><span>${money(total,currency)}</span></div><p class="foot">${esc(footer)}</p><div class="barcode"></div><script>window.onload=()=>{window.focus();window.print()}</script></body></html>`;const w=window.open("","_blank","width=420,height=800");if(w){w.document.write(html);w.document.close()}};
 return <div className="receipt-preview-wrap"><div className="receipt-preview-panel"><div className="preview-head"><div><h3>Test Receipt Preview</h3><small>This is how your receipt will look when printed.</small></div><button className="secondary" onClick={printTest}>▣ Test Print Receipt</button></div><div className="receipt-paper reference-receipt"><div className="receipt-rule-wide"></div><div className="receipt-brand">{header}</div><div className="receipt-center">{addr1}<br/>{addr2}<br/>{phone}<br/>{new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}<br/>Table No. <b>2</b> Bill No. 101</div><div className="receipt-rule-wide"></div><div className="receipt-item-head"><b>QTY</b><b>ITEM</b><b>PRICE</b></div><div className="receipt-item"><span>1</span><span>{sample.name}</span><span>{money(Number(sample.price),currency)}</span></div><div className="receipt-item"><span>1</span><span>{second.name}</span><span>{money(Number(second.price),currency)}</span></div><div className="receipt-rule-wide"></div><div className="receipt-pay"><b>VISA 2535</b><b>SALE</b></div><div className="receipt-line"><span>SUBTOTAL</span><span>{money(subtotal,currency)}</span></div><div className="receipt-line"><span>TAX</span><span>{money(tax,currency)}</span></div><div className="receipt-line"><span>TRANSACTION TYPE:</span><span>SALE</span></div><div className="receipt-line"><span>AUTHORIZATION:</span><span>APPROVED</span></div><div className="receipt-line"><span>PAYMENT CODE:</span><span>TEST-98871477</span></div><div className="receipt-line"><span>PAYMENT ID:</span><span>TEST-276131704</span></div><div className="receipt-line"><span>CARD READER:</span><span>SWIPED/CHIP</span></div><div className="receipt-rule-wide"></div><div className="receipt-total-row"><b>=TOTAL:</b><b>{money(total,currency)}</b></div><div className="receipt-thanks">{footer}</div><div className="receipt-barcode"></div></div><div className="printer-panel"><div><h4>Printer Detection</h4><small>Detect printer connection options available to this app.</small></div><button className="secondary" onClick={detect} disabled={detecting}>{detecting?"Checking…":"Detect Printers"}</button>{printer&&<div className="printer-results">{printer.map(x=><div className="printer-row" key={x.type}><span><b>{x.type}</b><small>{x.status}</small></span><em>{x.status.startsWith("Available")?"Available":"Manual / Native"}</em></div>)}</div>}<p className="note">Wi-Fi discovery and direct thermal printing require a native/mobile bridge or local print service. Bluetooth/USB pairing may require user permission.</p></div></div></div>
}

function SettingsModule({config,setConfig,products,setProducts,currency,role,setRole}){
 const [section,setSection]=useState("Overview"),[saved,setSaved]=useState(false);
 const [draft,setDraft]=useState(()=>({...config}));
 const sections=[["Overview","▦"],["Business Profile","🏪"],["POS & Checkout","▣"],["Modules","▦"],["Payments","₱"],["Tax","%"],["Receipts","▤"],["Inventory","▦"],["Users & Security","♙"],["Customers & Loyalty","♧"],["Language & Region","文"],["Appearance","◐"],["Notifications","●"],["Backup & Data","↥"],["Integrations","⚙"],["Audit Log","☷"]];
 const save=()=>{if(draft.ownerPin&&!/^\d{6}$/.test(String(draft.ownerPin))){alert("Owner PIN must be exactly 6 numerical digits.");return}const next={...config,...draft};localStorage.setItem("omnipos_config",JSON.stringify(next));if(next.ownerPin)localStorage.setItem("omnipos_owner_pin",next.ownerPin);setConfig(next);setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const update=(k,v)=>setDraft(d=>({...d,[k]:v}));
 return <section className="settings-page">
  <div className="settings-head"><div><h2>Settings</h2><p>Configure how OmniPOS operates for your business.</p></div>{section!=="Overview"&&<button className="primary" onClick={save}>{saved?"✓ Saved":"Save Changes"}</button>}</div>
  <div className="settings-layout"><nav className="settings-nav">{sections.map(([n,icon])=><button className={section===n?"active":""} onClick={()=>setSection(n)} key={n}><span>{icon}</span>{n}</button>)}</nav><div className="settings-content">
   {section==="Overview"&&<><div className="settings-overview-grid">{sections.slice(1,9).map(([n,icon])=><button className="setting-card" key={n} onClick={()=>setSection(n)}><span>{icon}</span><div><b>{n}</b><small>{n==="Business Profile"?"Business identity, address and contact details":n==="POS & Checkout"?"Orders, checkout and POS behavior":n==="Payments"?"Cash, cards and digital payment methods":n==="Tax"?"Tax rules and price configuration":n==="Receipts"?"Receipt layout and printing":n==="Inventory"?"Stock tracking and inventory rules":n==="Users & Security"?"Roles, permissions and authentication":"Customers, loyalty and profiles"}</small></div><em>›</em></button>)}</div><div className="current-config"><h3>Current Configuration</h3><div className="config-grid"><div><span>Business</span><b>{BUSINESS.find(x=>x[0]===config.business)?.[2]||config.business}</b></div><div><span>Language</span><b>{LANG.find(x=>x[0]===config.language)?.[2]||config.language}</b></div><div><span>Currency</span><b>{safeConfig.currency}</b></div><div><span>Tax</span><b>{config.tax}%</b></div><div><span>Theme</span><b>Dark</b></div><div><span>Items</span><b>{products.length}</b></div></div></div><button className="secondary" onClick={()=>{localStorage.removeItem("omnipos_config");setConfig(null)}}>Edit Business Setup</button></>}
   {section==="Business Profile"&&<SettingsCard title="Business Information" desc="Information used across receipts, reports and customer-facing documents."><Field label="Business Name" value={draft.businessName||"OmniPOS"} onChange={v=>update("businessName",v)}/><SelectField label="Business Type" value={draft.business} options={BUSINESS.map(x=>[x[0],x[2]])} onChange={v=>update("business",v)}/><Field label="Phone" value={draft.phone||""} placeholder="+63..." onChange={v=>update("phone",v)}/><Field label="Email" value={draft.email||""} onChange={v=>update("email",v)}/><Field label="Address" value={draft.address||""} onChange={v=>update("address",v)}/><Field label="Tax ID / Registration No." value={draft.taxId||""} onChange={v=>update("taxId",v)}/><LogoUpload value={draft.ownerLogo||""} onChange={v=>update("ownerLogo",v)}/></SettingsCard>}
   {section==="POS & Checkout"&&<SettingsCard title="POS Behavior" desc="Control how orders and checkout work at the register."><Toggle label="Allow negative inventory" value={draft.allowNegative||false} onChange={v=>update("allowNegative",v)}/><Toggle label="Allow guest checkout" value={draft.guestCheckout!==false} onChange={v=>update("guestCheckout",v)}/><Toggle label="Enable hold / suspended orders" value={draft.holdOrders!==false} onChange={v=>update("holdOrders",v)}/><Toggle label="Require payment confirmation" value={draft.paymentConfirmation!==false} onChange={v=>update("paymentConfirmation",v)}/><Toggle label="Enable tips" value={draft.tips||false} onChange={v=>update("tips",v)}/><Toggle label="Enable split payments" value={draft.splitPayments||false} onChange={v=>update("splitPayments",v)}/></SettingsCard>}
   {section==="Modules"&&<SettingsCard title="Modules & Features" desc="Turn optional capabilities on or off for this business. Disabled modules are removed from Staff navigation and can be enabled later without rebuilding the POS."><div className="module-grid">{Object.entries(DEFAULT_MODULES).map(([k,def])=><Toggle key={k} label={k[0].toUpperCase()+k.slice(1)} value={draft.modules?.[k]??def} onChange={v=>update("modules",{...(draft.modules||DEFAULT_MODULES),[k]:v})}/>)}</div><div className="setting-info"><b>Business mode</b><small>{draft.advancedMode===false?"Simple mode keeps the workspace focused.":"Advanced mode exposes configured operational modules."}</small></div><Toggle label="Advanced mode" value={draft.advancedMode!==false} onChange={v=>update("advancedMode",v)}/></SettingsCard>}
   {section==="Payments"&&<SettingsCard title="Payment Methods" desc="Choose the payment methods available during checkout."><Toggle label="Cash" value={draft.payCash!==false} onChange={v=>update("payCash",v)}/><Toggle label="Credit / Debit Card" value={draft.payCard||false} onChange={v=>update("payCard",v)}/><Toggle label="GCash" value={draft.payGCash||false} onChange={v=>update("payGCash",v)}/><Toggle label="Maya" value={draft.payMaya||false} onChange={v=>update("payMaya",v)}/><Toggle label="Bank Transfer" value={draft.payBank||false} onChange={v=>update("payBank",v)}/></SettingsCard>}
   {section==="Tax"&&<SettingsCard title="Tax Configuration" desc="Configure the default tax treatment used by POS and reports."><Toggle label="Tax enabled" value={draft.taxEnabled!==false} onChange={v=>update("taxEnabled",v)}/><Field label="Default Tax Rate (%)" type="number" value={draft.tax} onChange={v=>update("tax",v)}/><Field label="Tax Name" value={draft.taxName||"VAT"} onChange={v=>update("taxName",v)}/><Toggle label="Prices include tax" value={draft.pricesIncludeTax||false} onChange={v=>update("pricesIncludeTax",v)}/><Field label="Tax Registration No." value={draft.taxId||""} onChange={v=>update("taxId",v)}/></SettingsCard>}
   {section==="Receipts"&&<div className="receipt-settings-layout"><SettingsCard title="Receipt Settings" desc="Control printed and digital receipt content."><Toggle label="Print receipt automatically" value={draft.autoPrint!==false} onChange={v=>update("autoPrint",v)}/><Toggle label="Email receipt" value={draft.emailReceipt||false} onChange={v=>update("emailReceipt",v)}/><Toggle label="SMS receipt" value={draft.smsReceipt||false} onChange={v=>update("smsReceipt",v)}/><Field label="Receipt Header (Business Name)" value={draft.receiptHeader||draft.businessName||"OmniPOS Café"} onChange={v=>update("receiptHeader",v)}/><Field label="Address Line 1" value={draft.receiptAddress1||draft.address1||""} onChange={v=>update("receiptAddress1",v)}/><Field label="Address Line 2" value={draft.receiptAddress2||draft.address2||""} onChange={v=>update("receiptAddress2",v)}/><Field label="Phone Number" value={draft.receiptPhone||draft.phone||""} onChange={v=>update("receiptPhone",v)}/><Field label="Receipt Footer Message" value={draft.receiptFooter||"THANK YOU FOR DINING WITH US!\nPLEASE COME AGAIN"} onChange={v=>update("receiptFooter",v)}/><SelectField label="Receipt Width" value={draft.receiptWidth||"80mm"} options={[["80mm","80mm"],["58mm","58mm"],["A4","A4"]]} onChange={v=>update("receiptWidth",v)}/></SettingsCard><ReceiptPreview config={draft} products={products} currency={currency}/></div>}
   {section==="Inventory"&&<SettingsCard title="Inventory Rules" desc="Set defaults used by the Inventory module."><Toggle label="Track inventory by default" value={draft.trackInventory!==false} onChange={v=>update("trackInventory",v)}/><Toggle label="Warn when stock is low" value={draft.lowStockAlerts!==false} onChange={v=>update("lowStockAlerts",v)}/><Toggle label="Warn when stock reaches zero" value={draft.zeroStockAlerts!==false} onChange={v=>update("zeroStockAlerts",v)}/><Toggle label="Prevent selling out-of-stock items" value={draft.preventOutOfStock||false} onChange={v=>update("preventOutOfStock",v)}/><Field label="Default Reorder Point" type="number" value={draft.defaultReorder||10} onChange={v=>update("defaultReorder",v)}/></SettingsCard>}
   {section==="Users & Security"&&<SettingsCard title="Security & Access" desc="Security controls for staff accounts and sensitive POS actions."><Toggle label="Require PIN for refunds" value={draft.refundPin!==false} onChange={v=>update("refundPin",v)}/><Toggle label="Require manager approval for discounts" value={draft.discountApproval!==false} onChange={v=>update("discountApproval",v)}/><Toggle label="Require manager approval for voids" value={draft.voidApproval!==false} onChange={v=>update("voidApproval",v)}/><Toggle label="Auto-lock after inactivity" value={draft.autoLock!==false} onChange={v=>update("autoLock",v)}/><SelectField label="Auto-lock time" value={draft.lockTime||"15 minutes"} options={[["5 minutes","5 minutes"],["15 minutes","15 minutes"],["30 minutes","30 minutes"],["60 minutes","60 minutes"]]} onChange={v=>update("lockTime",v)}/><label className="setting-field">Owner PIN<input type="password" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="new-password" autoCorrect="off" autoCapitalize="off" spellCheck="false" name="settings-owner-pin" value={draft.ownerPin||""} onChange={e=>update("ownerPin",e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="6 digits"/></label><p className="note">The hidden image switch is only a trigger. Owner privileges require this PIN.</p><button className="secondary">Manage Users & Roles</button></SettingsCard>}
   {section==="Customers & Loyalty"&&<SettingsCard title="Customer & Loyalty" desc="Control customer information and optional loyalty features."><Toggle label="Enable customer profiles" value={draft.customerProfiles!==false} onChange={v=>update("customerProfiles",v)}/><Toggle label="Allow guest checkout" value={draft.guestCheckout!==false} onChange={v=>update("guestCheckout",v)}/><Toggle label="Enable loyalty program" value={draft.loyalty||false} onChange={v=>update("loyalty",v)}/><Field label="Points per ₱1 / base currency unit" type="number" value={draft.pointsPerUnit||1} onChange={v=>update("pointsPerUnit",v)}/></SettingsCard>}
   {section==="Language & Region"&&<SettingsCard title="Language & Region" desc="Regional preferences used throughout OmniPOS."><SelectField label="Language" value={draft.language} options={LANG.map(x=>[x[0],x[2]])} onChange={v=>update("language",v)}/><SelectField label="Currency" value={draft.currency} options={CUR.map(x=>[x[0],x[2]])} onChange={v=>update("currency",v)}/><SelectField label="Timezone" value={draft.timezone||"Asia/Manila"} options={[["Asia/Manila","Asia/Manila"],["Asia/Singapore","Asia/Singapore"],["UTC","UTC"]]} onChange={v=>update("timezone",v)}/><SelectField label="Date Format" value={draft.dateFormat||"MM/DD/YYYY"} options={[["MM/DD/YYYY","MM/DD/YYYY"],["DD/MM/YYYY","DD/MM/YYYY"],["YYYY-MM-DD","YYYY-MM-DD"]]} onChange={v=>update("dateFormat",v)}/><SelectField label="Time Format" value={draft.timeFormat||"12-hour"} options={[["12-hour","12-hour"],["24-hour","24-hour"]]} onChange={v=>update("timeFormat",v)}/></SettingsCard>}
   {section==="Appearance"&&<SettingsCard title="Appearance" desc="Customize the POS interface for speed and visibility."><SelectField label="Theme" value={draft.theme||"Dark"} options={[["Dark","Dark"],["Light","Light"],["System","System"]]} onChange={v=>update("theme",v)}/><SelectField label="Interface Density" value={draft.density||"Compact"} options={[["Compact","Compact"],["Comfortable","Comfortable"]]} onChange={v=>update("density",v)}/><SelectField label="Sidebar" value={draft.sidebar||"Expanded"} options={[["Expanded","Expanded"],["Collapsed","Collapsed"]]} onChange={v=>update("sidebar",v)}/></SettingsCard>}
   {section==="Notifications"&&<SettingsCard title="Notifications" desc="Choose operational alerts that matter to your team."><Toggle label="Low stock alerts" value={draft.notifyLow!==false} onChange={v=>update("notifyLow",v)}/><Toggle label="Out-of-stock alerts" value={draft.notifyOut!==false} onChange={v=>update("notifyOut",v)}/><Toggle label="Large transaction alerts" value={draft.notifyLarge||false} onChange={v=>update("notifyLarge",v)}/><Toggle label="Security alerts" value={draft.notifySecurity!==false} onChange={v=>update("notifySecurity",v)}/></SettingsCard>}
   {section==="Backup & Data"&&<SettingsCard title="Backup & Data Management" desc="Protect and export your POS data."><div className="backup-status"><span>Local data status</span><b>Stored on this device</b><small>Production deployments should use secure server/cloud backups.</small></div><div className="backup-actions"><button className="secondary" onClick={()=>{localStorage.setItem("omnipos_backup",JSON.stringify({config,products,timestamp:new Date().toISOString()}));alert("Backup created.")}}>Backup Now</button><button className="secondary" onClick={()=>{const data={config,products};const a=document.createElement("a");a.href="data:application/json;charset=utf-8,"+encodeURIComponent(JSON.stringify(data,null,2));a.download="omnipos-data.json";a.click()}}>Export JSON</button></div><p className="note">Restoring data should be permission-controlled and validated before replacing live records.</p></SettingsCard>}
   {section==="Integrations"&&<SettingsCard title="Integrations" desc="Connect external services without changing the core POS workflow.">{["Payment Gateways","Accounting","Loyalty","Email / SMS","Receipt Printer","Barcode Scanner","Cash Drawer"].map(x=><div className="integration-row" key={x}><span><b>{x}</b><small>Not connected</small></span><button className="secondary">Connect</button></div>)}</SettingsCard>}
   {section==="Audit Log"&&<SettingsCard title="Audit Log" desc="Track sensitive configuration and operational actions."><div className="audit-empty">Audit events will appear here as transactional and staff workflows are connected.</div></SettingsCard>}
  </div></div>
 </section>
}
function LogoUpload({value,onChange}){const read=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith("image/"))return;const r=new FileReader();r.onload=()=>onChange(r.result);r.readAsDataURL(f)};return <div className="logo-setting"><label>Owner Business Image</label><div className="logo-setting-row">{value?<img src={value} alt="Business logo preview"/>:<div className="logo-setting-empty"><PosLogo/></div>}<div><small>This image replaces the top-left brand area. Staff see the image, not an obvious owner switch.</small><label className="upload-btn">Choose Image<input type="file" accept="image/*" onChange={read}/></label>{value&&<button type="button" className="text-danger" onClick={()=>onChange("")}>Remove image</button>}</div></div></div>}
function SettingsCard({title,desc,children}){return <div className="settings-card"><h3>{title}</h3><p>{desc}</p><div className="settings-fields">{children}</div></div>}
function Field({label,value,onChange,type="text",placeholder=""}){return <label className="setting-field">{label}<input type={type} value={value??""} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,options,onChange}){return <label className="setting-field">{label}<select value={value??""} onChange={e=>onChange(e.target.value)}>{options.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label>}
function Toggle({label,value,onChange}){return <label className="toggle-row"><span>{label}</span><button type="button" className={"switch "+(value?"on":"")} onClick={()=>onChange(!value)}><i/></button></label>}



function UniversalModule({title,subtitle,children}){
 return <section className="panel universal-module"><div className="module-title"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section>
}
function OrdersModule({orders,setOrders,currency}){
 const [filter,setFilter]=useState("All");
 const shown=orders.filter(o=>filter==="All"||o.status===filter);
 const status=(o,next)=>setOrders(v=>v.map(x=>x.id===o.id?{...x,status:next}:x));
 return <UniversalModule title="Orders" subtitle="Manage held, open, paid and completed transactions."><div className="module-tabs">{["All","Held","Open","Paid","Completed","Cancelled","Refunded"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="table universal-table"><div className="row"><b>Order</b><span>Customer</span><span>Items</span><span>Total</span><span>Cashier</span><span>Status</span><span>Action</span></div>{shown.map(o=><div className="row" key={o.id}><b>#{String(o.id).slice(-6)}</b><span>{o.customer||"Walk-in"}</span><span>{o.items||0}</span><span>{money(o.total,currency)}</span><span>{o.cashier||"—"}</span><span>{o.status}</span><span><button className="row-action edit" onClick={()=>status(o,o.status==="Held"?"Open":"Completed")}>{o.status==="Held"?"Open":"Complete"}</button></span></div>)}{!shown.length&&<div className="products-empty">No orders found.</div>}</div></UniversalModule>
}
function CustomersModule({customers,setCustomers}){
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[query,setQuery]=useState("");
 const add=()=>{if(!name.trim())return;setCustomers(v=>[...v,{id:Date.now(),name:name.trim(),phone,email:"",points:0}]);setName("");setPhone("")};
 const shown=customers.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())||String(x.phone).includes(query));
 return <UniversalModule title="Customers" subtitle="Customer profiles, loyalty points and purchase relationships."><div className="inline-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Customer name"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone"/><button className="primary" onClick={add}>Add Customer</button><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></div><div className="table universal-table"><div className="row"><b>Name</b><span>Phone</span><span>Loyalty Points</span><span>Customer ID</span></div>{shown.map(c=><div className="row" key={c.id}><b>{c.name}</b><span>{c.phone||"—"}</span><span>{c.points||0}</span><span>#{c.id}</span></div>)}</div></UniversalModule>
}
function PurchasingModule({suppliers,setSuppliers,products,setProducts,currency}){
 const [supplier,setSupplier]=useState(""),[product,setProduct]=useState(products[0]?.id||""),[qty,setQty]=useState(""),[cost,setCost]=useState("");
 const receive=()=>{const q=Math.max(0,Number(qty));if(!q||!product)return;const now=new Date().toISOString();setProducts(v=>v.map(p=>p.id===Number(product)?{...p,stock:(Number(p.stock)||0)+q,cost:cost===""?p.cost:Number(cost),movements:[...(p.movements||[]),{date:now,type:"Purchase Received",qty:q,reason:"Purchase order",supplier:supplier||"—"}]}:p));setQty("");setCost("")};
 return <UniversalModule title="Purchasing" subtitle="Receive stock and maintain supplier relationships."><div className="inline-form"><select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Supplier</option>{suppliers.map(x=><option key={x.id}>{x.name}</option>)}</select><select value={product} onChange={e=>setProduct(e.target.value)}>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" min="0" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantity"/><input type="number" min="0" step=".01" value={cost} onChange={e=>setCost(e.target.value)} placeholder="Unit cost"/><button className="primary" onClick={receive}>Receive Stock</button></div><div className="table universal-table"><div className="row"><b>Supplier</b><span>Products</span><span>Stock receiving</span><span>Action</span></div>{suppliers.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{products.filter(p=>p.supplier===x.name).length||"—"}</span><span>Enabled</span><span><button className="row-action edit">Manage</button></span></div>)}</div></UniversalModule>
}
function SuppliersModule({suppliers,setSuppliers}){
 const [name,setName]=useState(""),[contact,setContact]=useState("");
 const add=()=>{if(!name.trim())return;setSuppliers(v=>[...v,{id:Date.now(),name:name.trim(),contact}]);setName("");setContact("")};
 return <UniversalModule title="Suppliers" subtitle="Supplier directory for purchasing and inventory sourcing."><div className="inline-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Supplier name"/><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Contact"/><button className="primary" onClick={add}>Add Supplier</button></div><div className="table universal-table"><div className="row"><b>Supplier</b><span>Contact</span><span>ID</span></div>{suppliers.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.contact||"—"}</span><span>#{x.id}</span></div>)}</div></UniversalModule>
}
function ExpensesModule({expenses,setExpenses,currency}){
 const [desc,setDesc]=useState(""),[amount,setAmount]=useState("");
 const add=()=>{if(!desc||!amount)return;setExpenses(v=>[{id:Date.now(),desc,amount:Number(amount),date:new Date().toISOString()},...v]);setDesc("");setAmount("")};
 return <UniversalModule title="Expenses" subtitle="Record operating expenses separately from sales transactions."><div className="inline-form"><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Expense description"/><input type="number" min="0" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount"/><button className="primary" onClick={add}>Record Expense</button></div><div className="table universal-table"><div className="row"><b>Description</b><span>Amount</span><span>Date</span></div>{expenses.map(x=><div className="row" key={x.id}><b>{x.desc}</b><span>{money(x.amount,currency)}</span><span>{new Date(x.date).toLocaleString()}</span></div>)}</div></UniversalModule>
}
function CashModule({shift,setShift,sales,currency}){
 const [opening,setOpening]=useState(""),[actual,setActual]=useState("");
 const open=()=>{if(opening==="")return;setShift({open:true,opening:Number(opening),openedAt:new Date().toISOString(),cashier:localStorage.getItem("omnipos_user")||""});setOpening("")};
 const cashSales=sales.filter(x=>(x.payment||"Cash")==="Cash").reduce((a,x)=>a+x.total,0);
 const expected=(shift?.opening||0)+cashSales;
 const close=()=>setShift({...shift,open:false,closedAt:new Date().toISOString(),actual:Number(actual||0),variance:Number(actual||0)-expected});
 return <UniversalModule title="Cash Register & Shifts" subtitle="Open, reconcile and close cashier sessions."><div className="shift-card"><div><small>Status</small><b>{shift?.open?"OPEN":"CLOSED"}</b></div><div><small>Opening Cash</small><b>{money(shift?.opening||0,currency)}</b></div><div><small>Expected Cash</small><b>{money(expected,currency)}</b></div><div><small>Variance</small><b>{money(shift?.variance||0,currency)}</b></div></div>{!shift?.open?<div className="inline-form"><input type="number" min="0" step=".01" value={opening} onChange={e=>setOpening(e.target.value)} placeholder="Opening cash"/><button className="primary" onClick={open}>Open Register</button></div>:<div className="inline-form"><input type="number" min="0" step=".01" value={actual} onChange={e=>setActual(e.target.value)} placeholder="Actual cash"/><button className="primary" onClick={close}>Close Register / Z Report</button></div>}</UniversalModule>
}
function GenericManagement({title,subtitle,items,label,addLabel,setItems}){
 const [name,setName]=useState("");
 return <UniversalModule title={title} subtitle={subtitle}><div className="inline-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder={label}/><button className="primary" onClick={()=>{if(name.trim()){setItems(v=>[...v,{id:Date.now(),name:name.trim(),status:"Active"}]);setName("")}}}>{addLabel}</button></div><div className="table universal-table"><div className="row"><b>Name</b><span>Status</span><span>ID</span></div>{items.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.status||"Active"}</span><span>#{x.id}</span></div>)}</div></UniversalModule>
}
function ReportsModule({sales,products,currency,taxRate}){
 const tx=Array.isArray(sales)?sales:[];
 const completed=tx.filter(x=>x&&x.status!=='Refunded'&&x.status!=='Cancelled');
 const gross=completed.reduce((a,x)=>a+(Number(x.total)||0),0);
 const refunds=tx.filter(x=>x&&x.status==='Refunded').reduce((a,x)=>a+(Number(x.total)||0),0);
 const cash=completed.filter(x=>x.payment==='Cash').reduce((a,x)=>a+(Number(x.total)||0),0);
 const card=completed.filter(x=>x.payment==='Card').reduce((a,x)=>a+(Number(x.total)||0),0);
 const digital=completed.filter(x=>['GCash','Maya','Bank Transfer','QR'].includes(x.payment)).reduce((a,x)=>a+(Number(x.total)||0),0);
 const units=completed.reduce((a,x)=>a+(Number(x.items)||0),0);
 const productMap={};
 completed.forEach(x=>(Array.isArray(x.lines)?x.lines:[]).forEach(i=>{const k=i.id??i.name;productMap[k]=productMap[k]||{name:i.name||'Item',qty:0,sales:0};productMap[k].qty+=Number(i.qty)||0;productMap[k].sales+=(Number(i.qty)||0)*(Number(i.price)||0)}));
 const top=Object.values(productMap).sort((a,b)=>b.sales-a.sales).slice(0,8);
 const tax=Number(taxRate)||0;
 const estimatedTax=tax>0?gross*(tax/(100+tax)):0;
 const net=gross-refunds;
 const today=new Date().toISOString().slice(0,10);
 const todaySales=completed.filter(x=>String(x.time||'').slice(0,10)===today);
 const todayTotal=todaySales.reduce((a,x)=>a+(Number(x.total)||0),0);
 return <UniversalModule title="Reports" subtitle="Sales, payment, product and reconciliation summaries from your POS records.">
  <div className="report-grid">
   <div className="report-card"><small>Gross Sales</small><b>{money(gross,currency)}</b></div>
   <div className="report-card"><small>Net Sales</small><b>{money(net,currency)}</b></div>
   <div className="report-card"><small>Transactions</small><b>{completed.length}</b></div>
   <div className="report-card"><small>Units Sold</small><b>{units}</b></div>
   <div className="report-card"><small>Today's Sales</small><b>{money(todayTotal,currency)}</b></div>
   <div className="report-card"><small>Refunds</small><b>{money(refunds,currency)}</b></div>
  </div>
  <div className="report-section"><h3>Payment Summary</h3><div className="table universal-table">
   <div className="row"><b>Method</b><span>Transactions</span><span>Amount</span></div>
   {['Cash','Card','GCash','Maya','Bank Transfer','QR'].map(method=>{const rows=completed.filter(x=>x.payment===method);const amount=rows.reduce((a,x)=>a+(Number(x.total)||0),0);return <div className="row" key={method}><b>{method}</b><span>{rows.length}</span><span>{money(amount,currency)}</span></div>})}
   <div className="row"><b>Estimated tax included</b><span>{tax}%</span><span>{money(estimatedTax,currency)}</span></div>
  </div></div>
  <div className="report-section"><h3>Top Products</h3><div className="table universal-table">
   <div className="row"><b>Product</b><span>Units</span><span>Sales</span></div>
   {top.length?top.map(x=><div className="row" key={String(x.name)}><b>{x.name}</b><span>{x.qty}</span><span>{money(x.sales,currency)}</span></div>):<div className="empty">No completed sales yet.</div>}
  </div></div>
  <div className="report-section"><h3>Inventory Snapshot</h3><div className="table universal-table">
   <div className="row"><b>Product</b><span>Stock</span><span>Tracking</span></div>
   {(Array.isArray(products)?products:[]).map(p=><div className="row" key={p.id}><b>{p.name}</b><span>{p.track===false?'—':Math.max(0,Number(p.stock)||0)}</span><span>{p.track===false?'Service':'Inventory'}</span></div>)}
  </div></div>
 </UniversalModule>
}

function App(){
 const[user,setUser]=useState(()=>localStorage.getItem('omnipos_user'));
 const[role,setRole]=useState(()=>localStorage.getItem('omnipos_role')||'owner');
 const[config,setConfig]=useState(()=>readJSON('omnipos_config',null));
 const[products,setProducts]=useState(()=>{const raw=readJSON('omnipos_products',DEFAULT);const list=Array.isArray(raw)?raw:DEFAULT;return list.map(p=>p&&typeof p==='object'?(p.track!==false?{...p,stock:Math.max(0,Number(p.stock)||0)}:p):null).filter(Boolean)});
 const[sales,setSales]=useState(()=>readArray('omnipos_sales'));
 const[orders,setOrders]=useState(()=>readArray('omnipos_orders'));
 const[customers,setCustomers]=useState(()=>readArray('omnipos_customers'));
 const[suppliers,setSuppliers]=useState(()=>readArray('omnipos_suppliers'));
 const[expenses,setExpenses]=useState(()=>readArray('omnipos_expenses'));
 const[shift,setShift]=useState(()=>readJSON('omnipos_shift',null));
 const[tab,setTab]=useState('Sale'),[cart,setCart]=useState([]),[search,setSearch]=useState(''),[cat,setCat]=useState('All');
 const[secret,setSecret]=useState(false),[pin,setPin]=useState(''),[pinError,setPinError]=useState(''),[cmd,setCmd]=useState(false),[payment,setPayment]=useState(false),[customerId,setCustomerId]=useState('');
 const[online,setOnline]=useState(navigator.onLine),[syncPending,setSyncPending]=useState(()=>Number(localStorage.getItem('omnipos_sync_pending')||0));
 const audit=(action,detail)=>{const a=readArray('omnipos_audit');a.unshift({id:Date.now(),at:new Date().toISOString(),user,role,action,detail});localStorage.setItem('omnipos_audit',JSON.stringify(a.slice(0,1000)))};
 useEffect(()=>localStorage.setItem('omnipos_products',JSON.stringify(products)),[products]);
 useEffect(()=>localStorage.setItem('omnipos_sales',JSON.stringify(sales)),[sales]);
 useEffect(()=>localStorage.setItem('omnipos_orders',JSON.stringify(orders)),[orders]);
 useEffect(()=>localStorage.setItem('omnipos_customers',JSON.stringify(customers)),[customers]);
 useEffect(()=>localStorage.setItem('omnipos_suppliers',JSON.stringify(suppliers)),[suppliers]);
 useEffect(()=>localStorage.setItem('omnipos_expenses',JSON.stringify(expenses)),[expenses]);
 useEffect(()=>localStorage.setItem('omnipos_shift',JSON.stringify(shift)),[shift]);
 useEffect(()=>{const on=()=>{setOnline(true);const n=Number(localStorage.getItem('omnipos_sync_pending')||0);if(n){setSyncPending(0);localStorage.setItem('omnipos_sync_pending','0')}};const off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 if(!user)return <Login done={setUser}/>;
 if(!config?.setupDone)return <Setup done={()=>setConfig(readJSON('omnipos_config',null))}/>;
 const modules={...DEFAULT_MODULES,...(config.modules&&typeof config.modules==='object'?config.modules:{})};
 const safeConfig={...config,tax:Number(config.tax)||0,currency:config.currency||'PHP'};
 const basePerm={owner:{sale:true,inventory:true,products:true,reports:true,customers:true,purchasing:true,suppliers:true,expenses:true,loyalty:true,tables:true,appointments:true,delivery:true,settings:true},manager:{sale:true,inventory:true,products:true,reports:true,customers:true,purchasing:true,suppliers:true,expenses:true,loyalty:true,tables:true,appointments:true,delivery:true,settings:false},staff:{sale:true,inventory:false,products:false,reports:false,customers:true,purchasing:false,suppliers:false,expenses:false,loyalty:true,tables:true,appointments:true,delivery:true,settings:false}}[role]||{sale:true};
 const can=x=>basePerm[x]!==false&&(x==="sale"||modules[x]!==false);
 const nav=[["Sale","sale","▣"],["Orders","orders","◉"],["Inventory","inventory","▤"],["Products","products","◫"],["Customers","customers","♙"],["Reports","reports","◒"],["More","more","⋯"]].filter(x=>x[0]==="Orders"||x[0]==="More"||can(x[1]));
 const more=[["Purchasing","purchasing"],["Suppliers","suppliers"],["Expenses","expenses"],["Loyalty","loyalty"],["Tables","tables"],["Appointments","appointments"],["Delivery","delivery"],["Cash Register","cash"],["Audit Log","audit"],["Printer Manager","printer"]];
 if(role==="owner")nav.push(["Settings","settings","⚙"]);
 useEffect(()=>{if(!nav.some(x=>x[0]===tab)&&tab!=="More")setTab('Sale')},[role,config.modules,tab]);
 const cats=['All',...new Set(products.map(p=>p.category))],shown=products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(search.toLowerCase()));
 const sub=cart.reduce((a,i)=>a+i.price*i.qty,0),discount=0,tax=safeConfig.taxEnabled===false?0:sub*(safeConfig.tax/100),total=Math.max(0,sub-discount+tax);
 const add=p=>{if(p.track!==false){const available=Math.max(0,Number(p.stock)||0),inCart=cart.find(i=>i.id===p.id)?.qty||0;if(available<=0||inCart>=available)return}setCart(v=>{let q=v.find(i=>i.id===p.id);return q?v.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...v,{...p,qty:1}]})};
 const change=(id,d)=>setCart(v=>v.map(i=>{if(i.id!==id)return i;const p=products.find(x=>x.id===id),max=p?.track!==false?Math.max(0,Number(p.stock)||0):Infinity;return {...i,qty:Math.max(0,Math.min(max,i.qty+d))}}).filter(i=>i.qty>0));
 const completeSale=(method="Cash",amountPaid=total)=>{if(!cart.length)return;const invalid=cart.find(i=>{const p=products.find(x=>x.id===i.id);return p?.track!==false&&i.qty>Math.max(0,Number(p.stock)||0)});if(invalid){alert(`${invalid.name} does not have enough stock.`);return}const now=new Date().toISOString(),items=cart.map(i=>({id:i.id,name:i.name,category:i.category,qty:i.qty,price:i.price,cost:i.cost??i.price*.45})),tx={id:Date.now(),items:items.reduce((a,i)=>a+i.qty,0),total,time:now,payment:method,amountPaid:Number(amountPaid),change:Math.max(0,Number(amountPaid)-total),lines:items,discount,refund:0,cashier:user,role,location:config.location||"Main Location",customer:customers.find(c=>c.id===Number(customerId))?.name||"Walk-in",status:"Completed"};setSales(v=>[tx,...v]);setOrders(v=>[tx,...v]);setProducts(v=>v.map(p=>{const i=cart.find(q=>q.id===p.id);return i&&p.track!==false?{...p,stock:Math.max(0,p.stock-i.qty),movements:[...(p.movements||[]),{date:now,type:"Sale",qty:-i.qty,reason:"POS sale",supplier:"—"}]}:p}));audit("Sale completed",`#${tx.id} • ${money(total,config.currency)} • ${method}`);setCart([]);setPayment(false);setCustomerId("");if(!online){const n=Number(localStorage.getItem('omnipos_sync_pending')||0)+1;localStorage.setItem('omnipos_sync_pending',String(n));setSyncPending(n)}};
 const holdOrder=()=>{if(!cart.length)return;const o={id:Date.now(),items:cart.reduce((a,i)=>a+i.qty,0),total,status:"Held",lines:cart,cashier:user,customer:customers.find(c=>c.id===Number(customerId))?.name||"Walk-in",time:new Date().toISOString()};setOrders(v=>[o,...v]);audit("Order held",`#${o.id}`);setCart([]);setCustomerId("")};
 const switchAccess=()=>{if(role==="owner"){localStorage.setItem('omnipos_role','staff');setRole('staff');setTab('Sale');audit("Entered Staff Mode","Owner switched to Staff");return}setPin("");setPinError("");setSecret(true)};
 const verifyOwner=()=>{const expected=localStorage.getItem("omnipos_owner_pin")||String(config.ownerPin||"");if(/^\d{6}$/.test(pin)&&/^\d{6}$/.test(expected)&&pin===expected){localStorage.setItem('omnipos_role','owner');setRole('owner');setSecret(false);setPin("");audit("Entered Owner Mode","Staff elevation verified")}else setPinError("Incorrect 6-digit Owner PIN.")};
 const go=x=>{setCmd(false);setTab(x)};
 return <div className="app"><aside><div className="brand secret-brand"><div className="brand-image" onDoubleClick={switchAccess} onTouchEnd={e=>{if(e.detail===2)switchAccess()}}>{config.ownerLogo?<img src={config.ownerLogo} alt="Business"/>:<div className="logo-placeholder"><PosLogo/></div>}</div><small>{BUSINESS.find(x=>x[0]===config.business)?.[2]}</small></div>{nav.map(([x,key,icon])=><button className={'nav '+(tab===x?'active':'')} onClick={()=>setTab(x)} key={x}>{icon} {x}</button>)}<div className="account"><small>{user}</small><small className="account-brand">OmniPOS</small><button className="command-mini" onClick={()=>setCmd(true)}>⌘ Search</button><button onClick={()=>{audit("Sign out","User signed out");localStorage.removeItem('omnipos_user');localStorage.removeItem('omnipos_role');setUser(null)}}>Sign out</button></div></aside>
 <main><header><div><h1>{tab}</h1><span>{BUSINESS.find(x=>x[0]===config.business)?.[2]||"Universal POS"} • {shift?.open?"Register Open":"Register Closed"}</span></div><div className="status">{online?"● Online":"● Offline"} {syncPending?` • ${syncPending} pending`:''}</div></header>
 {tab==='Sale'&&<section className="sale"><div className="catalog" autoComplete="off"><input className="search" type="search" name="omnipos-product-search" autoComplete="off" autoCorrect="off" autoCapitalize="off" spellCheck="false" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…"/><div className="cats">{cats.map(x=><button className={'pill '+(cat===x?'selected':'')} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="grid">{shown.map(p=><button className="product" onClick={()=>add(p)} disabled={p.track!==false&&((Number(p.stock)||0)<=0||((cart.find(i=>i.id===p.id)?.qty||0)>=(Number(p.stock)||0)))} key={p.id}><div className="cup">🧋</div><b>{p.name}</b><span>{money(p.price,config.currency)}</span><small className={p.track!==false&&Number(p.stock)<=10?'warn':''}>{p.track===false?'Service':Math.max(0,Number(p.stock)||0)+' in stock'}</small></button>)}</div></div><div className="cart"><div className="carthead"><b>Current Sale</b><span>{cart.reduce((a,i)=>a+i.qty,0)} items</span></div>{customers.length>0&&<select className="customer-select" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Walk-in Customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<div className="cartitems">{cart.length?cart.map(i=><div className="cartitem" key={i.id}><div><b>{i.name}</b><small>{money(i.price,config.currency)} each</small></div><div className="qty"><button onClick={()=>change(i.id,-1)}>−</button><b>{i.qty}</b><button onClick={()=>change(i.id,1)}>+</button></div><strong>{money(i.price*i.qty,config.currency)}</strong></div>):<div className="empty">No items yet<br/><small>Select a product to add it.</small></div>}</div><div className="totals"><div>Subtotal <b>{money(sub,config.currency)}</b></div><div>Tax ({config.tax}%) <b>{money(tax,config.currency)}</b></div><div className="total">Total <b>{money(total,config.currency)}</b></div><div className="cart-actions"><button className="secondary" onClick={holdOrder} disabled={!cart.length}>Hold</button><button className="primary full" onClick={()=>setPayment(true)} disabled={!cart.length}>Pay • {money(total,config.currency)}</button></div></div></div></section>}
 {tab==='Orders'&&<OrdersModule orders={orders} setOrders={setOrders} currency={safeConfig.currency}/>}
 {tab==='Inventory'&&<Inventory products={products} setProducts={setProducts} currency={safeConfig.currency}/>}
 {tab==='Products'&&<Products products={products} setProducts={setProducts} currency={safeConfig.currency}/>}
 {tab==='Customers'&&<CustomersModule customers={customers} setCustomers={setCustomers}/>}
 {tab==='Reports'&&<ReportsModule sales={sales} products={products} currency={safeConfig.currency} taxRate={config.tax}/>}
 {tab==='Settings'&&<SettingsModule config={config} setConfig={setConfig} products={products} setProducts={setProducts} currency={safeConfig.currency} role={role} setRole={setRole}/>}
 {tab==='More'&&<UniversalModule title="More" subtitle="Business capabilities enabled by your POS configuration."><div className="more-grid">{more.filter(([n,k])=>k==="cash"||can(k)||role==="owner").map(([n,k])=><button className="more-card" key={k} onClick={()=>setTab(n)}><b>{n}</b><small>Open {n.toLowerCase()}</small></button>)}</div></UniversalModule>}
 {tab==='Purchasing'&&<PurchasingModule suppliers={suppliers} setSuppliers={setSuppliers} products={products} setProducts={setProducts} currency={safeConfig.currency}/>}
 {tab==='Suppliers'&&<SuppliersModule suppliers={suppliers} setSuppliers={setSuppliers}/>}
 {tab==='Expenses'&&<ExpensesModule expenses={expenses} setExpenses={setExpenses} currency={safeConfig.currency}/>}
 {tab==='Loyalty'&&<GenericManagement title="Loyalty" subtitle="Manage loyalty program members and program records." items={customers} label="Member / customer" addLabel="Add Member" setItems={setCustomers}/>}
 {tab==='Tables'&&<GenericManagement title="Tables" subtitle="Table management foundation for restaurant and café workflows." items={readArray("omnipos_tables")} label="Table name / number" addLabel="Add Table" setItems={v=>{localStorage.setItem("omnipos_tables",JSON.stringify(v));setTab("Tables")}}/>}
 {tab==='Appointments'&&<GenericManagement title="Appointments" subtitle="Appointment scheduling foundation for service businesses." items={readArray("omnipos_appointments")} label="Appointment / client" addLabel="Add Appointment" setItems={v=>{localStorage.setItem("omnipos_appointments",JSON.stringify(v));setTab("Appointments")}}/>}
 {tab==='Delivery'&&<GenericManagement title="Delivery" subtitle="Delivery order tracking foundation." items={readArray("omnipos_delivery")} label="Order / recipient" addLabel="Add Delivery" setItems={v=>{localStorage.setItem("omnipos_delivery",JSON.stringify(v));setTab("Delivery")}}/>}
 {tab==='Cash Register'&&<CashModule shift={shift} setShift={v=>{setShift(v);localStorage.setItem("omnipos_shift",JSON.stringify(v));audit(v?.open?"Register opened":"Register closed","Cash shift")}} sales={sales} currency={safeConfig.currency}/>}
 {tab==='Audit Log'&&<UniversalModule title="Audit Log" subtitle="Sensitive actions are recorded locally in chronological order."><div className="table universal-table">{readArray("omnipos_audit").map(x=><div className="row" key={x.id}><b>{new Date(x.at).toLocaleString()}</b><span>{x.user}</span><span>{x.role}</span><span>{x.action}</span><span>{x.detail}</span></div>)}</div></UniversalModule>}
 {tab==='Printer Manager'&&<UniversalModule title="Printer Manager" subtitle="Connection-ready printer management for Wi-Fi, Bluetooth and wired devices."><ReceiptPreview config={config} products={products} currency={safeConfig.currency}/></UniversalModule>}
 </main>
 {payment&&<div className="modalback"><div className="modal payment-modal"><button className="close" onClick={()=>setPayment(false)}>×</button><div className="step">CHECKOUT</div><h2>Choose Payment</h2><div className="payment-total">{money(total,config.currency)}</div><div className="payment-methods">{["Cash","Card","GCash","Maya","Bank Transfer","QR"].map(m=><button className="payment-method" key={m} onClick={()=>{if(m==="Cash"){const a=prompt(`Cash received (${safeConfig.currency})`,String(total));if(a!==null&&Number(a)>=total)completeSale(m,Number(a));else if(a!==null)alert("Amount received is less than the sale total.")}else completeSale(m,total)}}>{m}</button>)}</div><button className="secondary full" onClick={()=>setPayment(false)}>Cancel</button></div></div>}
 {secret&&<div className="modalback"><div className="modal secret-modal"><button className="close" onClick={()=>setSecret(false)}>×</button><div className="step">OWNER ACCESS</div><h2>Enter Owner PIN</h2><p className="note">Enter the six-digit Owner PIN.</p><input className="owner-pin" type="password" inputMode="numeric" autoComplete="off" maxLength={6} pattern="[0-9]{6}" autoFocus value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} onKeyDown={e=>e.key==="Enter"&&verifyOwner()} placeholder="6-digit Owner PIN"/>{pinError&&<div className="pin-error">{pinError}</div>}<div className="actions"><button className="secondary" onClick={()=>setSecret(false)}>Cancel</button><button className="primary" onClick={verifyOwner}>Enter Owner Mode</button></div></div></div>}
 {cmd&&<div className="modalback" onClick={()=>setCmd(false)}><div className="modal command-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setCmd(false)}>×</button><div className="step">QUICK NAVIGATION</div><h2>Search OmniPOS</h2><input autoFocus autoComplete="off" placeholder="Type a module…" onKeyDown={e=>{if(e.key==="Enter")go(e.currentTarget.value.trim())}}/><div className="command-list">{[...nav,...more.map(x=>[x[0],x[1],"→"])].map(x=><button onClick={()=>go(x[0])} key={x[0]}>{x[2]} {x[0]} <span>→</span></button>)}</div></div></div>}
 </div>
}

class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={error:null}}static getDerivedStateFromError(error){return{error}}componentDidCatch(error,info){console.error(error,info)}render(){return this.state.error?<div>OmniPOS could not load this screen</div>:this.props.children}}

createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
